AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    product-scraper

Resources:
    ChromePuppeteerLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            Description: Serverless Chrome/Puppeteer Layer
            ContentUri: layers/puppeteer/
            CompatibleRuntimes:
                - nodejs14.x
        Metadata:
            BuildMethod: nodejs14.x

    ScraperFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: app.lambdaHandler
            Timeout: 120
            MemorySize: 2048
            Runtime: nodejs14.x
            Events:
                Scraper:
                    Type: Api
                    Properties:
                        Path: /scrape
                        Method: get
            Layers:
                - !Ref ChromePuppeteerLayer

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                EntryPoints:
                    - app.ts

Outputs:
    ScraperApi:
        Description: "API Gateway endpoint URL for Prod stage for Hello World function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scraper/"
